### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by jarac794** [websu-io/websu#20]
I am trying to analyze a website and it throws me this error, would you know a possible solution, I am using docker: 8000

rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by samos123** [comment]
Try using the docker-compose steps from the README, if it still doesn't work please post more details such as steps to reproduce

**Comment by jarac794** [comment]
Hello, thanks for answering,
 I have done the indicated steps again, but apparently the problem persists with pages that take a long time to analyze

Request Method: POST


Error: Request failed with status code 500
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.handleLoad (xhr.js:62:1)


With pages that have less weight, it analyzes without a problem.


will it be timeout? where can i increase your time?

**Comment by samos123** [comment]
It might be this timeout but it's set to 45 seconds: https://github.com/websu-io/websu/blob/5fdfd31684b640f5f224dfec89c78024d290b83e/pkg/api/app.go#L270

It could be that you're running websu in an environment with very poor internet connectivity. I don't recommend increasing the timeout to more than 45 seconds.

**Comment by jarac794** [comment]
I think that if one of the problems could be the network but I have increased it 5 more seconds and it has already worked for me Thank you

**Comment by samos123** [comment]
I guess it should be a configurable timeout in that case. Thanks for reporting this and happy to see someone taking Websu being used outside of https://websu.io

I would like to learn more how you plan to use Websu if you're willing to share :)

I'm keeping it open and change to a FR for configurable timeouts.

**Comment by jarac794** [comment]
> Supongo que debería ser un tiempo de espera configurable en ese caso. Gracias por informar esto y feliz de ver a alguien tomando Websu y usándolo fuera de https://websu.io
> 
> Me gustaría obtener más información sobre cómo planea usar Websu si está dispuesto a compartir :)
> 
> Lo mantengo abierto y cambio a un FR para tiempos de espera configurables.

Thank you for the contribution that you are giving, if I am offering it for free to everyone so that they can analyze it faster, it is much more friendly web.dev many common users are unaware of the lighthouse tool and more only reach pagespeed, with your contribution it is a way more accessible and the other is that it allows you to analyze it for desktop or mobile, webdev only analyzes for cell phones I don't know why and the possibility of using several regions I think is very excellent although I haven't been able to configure that part or I don't know why the selector leaves me blank :) so through my agency I offer it for free and well maybe later we can contribute with other tools through it or join others that are here github

**Comment by samos123** [comment]
Thanks for sharing! You will have to start deploying locations across the world and then add the locations using the location API endpoint. You can take a look at the script I use to make Websu available in all regions that Cloud Run is available in: https://github.com/websu-io/websu/blob/master/scripts/deploy-lighthouse-servers.py

I also want to mention that the current UI of websu.io is not open source because it didn't make sense to add authentication and static pages like privacy policies in the OSS version of the UI. So I currently maintain 2 versions of the UI and majority of my time is now spent on the SaaS UI version while making sure the OSS UI doesn't break.

Please keep the feedback coming on what features would attract more users. My focus for now is to work on monitoring and more dashboards so people can analyze the performance of a specific website over time and get alerted when performance gets degraded.

**Comment by jarac794** [comment]
Thank you very much, I will be reviewing the scripts, something interesting that you can do a site vs site comparative option where you can compare your website with that of your competition or your same website but in comparison January vs. March for example

**Comment by jarac794** [comment]
and the other one, as I was saying, being able to update the lighthouse would be good because you add the accessibility metric
